### ISSUE TITLE
tiller-noauth scenario requires helm2, client machine has helm3. 

### ISSUE THREAD

**Issue by mrintern** [raesene/kube_security_lab#20]
@raesene 

To complete the tiller-noauth scenario helm2 is required. There are breaking changes in helm 3 (for one, the `--host` flag is no longer recognized) , rendering the scenario walkthrough commands useless. One possible solution is updating the commands to reflect helm3 syntax. Another solution is shipping the client container with helm2.

![image](https://user-images.githubusercontent.com/24460340/187088948-efa00769-ddd7-4779-b1de-d123868f6378.png)

**Comment by raesene** [comment]
yeah I think it'll work best if we have a helm2 binary (not even sure the helm3 client can talk to Tiller). I've added the `/usr/local/bin/helm2` binary to the alpine-containertools image that's used for the client so that *should* work ok...

**Comment by mrintern** [comment]
@raesene Noted, as soon as you push the changes i'll test it out and report back.

**Comment by raesene** [comment]
it should work ok now :) the container image for the client is `raesene/alpine-containertools` and that one auto-rebuilds when I push a change. You might need to re-pull the image, but it should have helm2 when you do!
