### ISSUE TITLE
etcd noauth exercise is broken

### ISSUE THREAD

**Issue by smarticu5** [raesene/kube_security_lab#9]
Recent versions of kind/kubeadm/etcd seem to have changed the default behaviour now, so there's a default value (- --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt) which overrides client-cert-auth=false, so auth is required. 

I reckon either moving to an older version of kind, removing the etcd flag at config time, or hacking a post-deploy fix in Ansible will all work to fix this, not sure what's cleanest.

**Comment by raesene** [comment]
Fixed in the latest HEAD version.  Looks like this was introduced in 1.17 or 1.18.  moved the etcdnoauth exercise back to 1.16.9
